### ISSUE TITLE
ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by error10** [gpmidi/zabbix-apache-stats#1]
Attempting to run fetch.py on a CentOS 5.10 system returns the following error:

```
Traceback (most recent call last):
  File "/etc/zabbix/bin/fetch.py", line 224, in <module>
    data = parse(data = data)
  File "/etc/zabbix/bin/fetch.py", line 77, in parse
    for (key, val) in csvobj:
ValueError: need more than 1 value to unpack
```

This is very strange code. It works perfectly on my Debian and Ubuntu systems; this is the first CentOS box I have tried to run it on.

I threw in a `print data` just before line 77 to verify that it was actually seeing the Apache server status, and the status appeared to be present and valid.

The only other change I made to the script was in line 1, which I changed to:

```
#!/usr/bin/python26
```

to try to rule out any problem with Python 2.4.

The box is running:

CentOS 5.10
python26-2.6.8-2.el5

My command line was:

```
/etc/zabbix/bin/fetch.py -c $(hostname) -z monitor.example.com -l http://localhost/whm-server-status
```

**Comment by jva5007** [comment]
I tried to run this script from our monitoring server for a remote host running Apache 2.4.16, but when I excecute cron, it returns the following error.

Traceback (most recent call last):
  File "/usr/local/plugin/fetch.py", line 225, in <module>
    data = parse(data = data)
  File "/usr/local/plugin/fetch.py", line 78, in parse
    for (key, val) in csvobj:
ValueError: need more than 1 value to unpack

I have added hostname before each item key in the template.

When I add print data in 77th line in the script it shows correct data from apache server along with the error above. I also checked with 'print repr(csvobj)' but it shows the following.

<_csv.reader object at 0x7f04feca5a60>
Traceback (most recent call last):
  File "/usr/local/plugin/fetch.py", line 225, in <module>
    data = parse(data = data)
  File "/usr/local/plugin/fetch.py", line 78, in parse
    for (key, val) in csvobj:
ValueError: need more than 1 value to unpack

remote host in an amazon ec2 instance.
