### ISSUE TITLE
running on localhost

### ISSUE THREAD

**Issue by shawtux** [gpmidi/zabbix-apache-stats#3]
when running fetch.py on localhost with zabbix on localhost and apache on localhost, sender runs but no test pass. the instructions in the wiki were followed as well.

/usr/bin/python ZabbixApacheUpdater.py -s /usr/local/bin/zabbix_sender -z localhost -c 127.0.0.1
zabbix_sender [5946]: DEBUG: answer [{
	"response":"success",
	"info":"processed: 0; failed: 20; total: 20; seconds spent: 0.001798"}]
info from server: "processed: 0; failed: 20; total: 20; seconds spent: 0.001798"
sent: 20; skipped: 0; total: 20
Usage: ApacheStatsForZabbix [-z <Zabbix hostname or IP>] [-o <Apache hostname or IP>]

ApacheStatsForZabbix: error: An error occurred while sending values to the Zabbix server

**Comment by gpmidi** [comment]
Closing as this is a very old issue; shawtux probably is long past this. If not, he can reopen it.
